name: Cypress E2E Tests
on:
  workflow_dispatch:

jobs:
  cypress-run:
    env:
      CYPRESS_host: https://whs-server1.whscrm.selise.tech/auth
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Set Date
        id: date
        run: echo "currentDate=$(TZ=Asia/Thimphu date +%d-%b-%Y\ %H:%M:%S\ %Z)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: qa/different-browser

      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Install Dependencies
        run: yarn install

      - name: Setup firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}
      - run: |
          echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
          ${{ steps.setup-firefox.outputs.firefox-path }} --version

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          record: true
          parallel: true
          project: ./
          spec: ./cypress/e2e/
          wait-on: https://whs-server1.whscrm.selise.tech/auth
          config-file: cypress.config.js
          browser: firefox

        env:
          COMMIT_INFO_MESSAGE: 'Test ${{ steps.date.outputs.currentDate }} '
          COMMIT_INFO_AUTHOR: 'PAA'
